#!/usr/bin/env python3
# system/py #
#
# python system/py

# ~ ~ ~ ~ ~ #

# IMPORTS #
import sys
import subprocess
from pathlib import Path
#
# IMPORTS #


# VARS #
bd_vsc = ".vscode"
v_slash = "/"
#|
#|
BASE_LINK = "https://raw.githubusercontent.com"
BASE_DIR = Path(bd_vsc).joinpath(*[
    "system", "py", ])
#
GIT_USER = "Minecube1510"
GU_REPO = "s4mpl3_m3m0ry"
GUR_BRANCH = "work-dev"
#
GITTER_LINK = v_slash.join([BASE_LINK,
    GIT_USER, GU_REPO, GUR_BRANCH, ])
BD_LINK = v_slash.join([GITTER_LINK,
    str(BASE_DIR), ])
#
REDIC_LINK = BASE_DIR if BASE_DIR.exists() else BD_LINK
# VARS #


# FUNCTINGS - SYSTEM #
def is_py_script (file_path):
    req_py = ("#!/usr/bin/env python")
    #
    # Auto valid kalau .py
    if not file_path.is_file():
        return False
    if file_path.suffix == ".py":
        return True
    #
    # Cek shebang
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            first_line = f.readline().strip()
        #
        return first_line.startswith(req_py)
    #
    except Exception:
        return False
def normalize_comm (full_path, relative):
    relative_str = str(relative).replace("\\", ":")
    #
    if is_py_script(full_path):
        if relative.suffix == ".py":
            return relative_str[:-3]
        #
        return relative_str
    return None
#
def get_all_commands ():
    comm_files = []
    for item in REDIC_LINK.rglob("*"):
        if not item.is_file():
            continue
        #
        relates = item.relative_to(REDIC_LINK)
        comm_names = normalize_comm(item, relates)
        #
        comm_files.append(comm_names)
    #
    return comm_files
def print_comms (comm_files):
    p_signter = (">+~=-  PY-SYS Commands  -=~+<")
    #
    print(p_signter)
    for cmd in comm_files:
        print(f"  [-] {cmd}")
    print((p_signter) + ("\n"))
#
# FUNCTINGS - SYSTEM #


# FUNCTINGS - FINAL #
def resolve_target (comm_file):
    command_path = comm_file.replace(":", v_slash)
    target_maps = [
        f"{command_path}.py",
        command_path,
    ]
    for target in target_maps:
        target_f = (REDIC_LINK / target)
        #
        if target_f.exists():
            return target_f
    #
    return None
def execute_target (target_f, extra_args):
    #
    subprocess.run(
        [sys.executable, str(target_f), *extra_args],
        check=True
    )
#
def sys_work ():
    #
    comm_files = get_all_commands()
    #
    if len(sys.argv) < 2:
        print_comms(comm_files)
        return
    #
    comm_file = sys.argv[1]
    target_f = resolve_target(comm_file)
    if target_f is None:
        msg_404 = f"Command `{comm_file}` is Not-Found..."
        print(msg_404)
        return
    #
    extra_args = sys.argv[2:]
    execute_target(target_f, extra_args)
#
def main ():
    sys_work()
#
# FUNCTINGS - FINAL #


# DISPLAY #
if __name__ == "__main__":
    main()
# DISPLAY #

# ~ ~ ~ ~ ~ #


#
