#!/usr/bin/env python3
# system/py #
#
# python system/py

# ~ ~ ~ ~ ~ #

# IMPORTS #
import sys
import subprocess
#
import requests
from pathlib import Path
import tempfile
#
# IMPORTS #


# VARS #
bd_vsc = ".vscode"
#
class Var:
    blank = ""
    #
    pipe = "|"
    quest = "?"
    slash = "/"
    #
    enter = "\n"
#
http = "http"
ht_s = "s://"
https = http + ht_s
#|
#|
B_RAW_LINK = https + "raw.githubusercontent.com"
B_API_LINK = https + "api.github.com/repos"
BASE_DIR = Path(bd_vsc).joinpath(*[
    "system", "py", ])
#
BD_EXISTS = BASE_DIR.exists()
#
GIT_USER = "Minecube1510"
GU_REPO = "s4mpl3_m3m0ry"
GUR_BRANCH = "work-dev"
#
LAST_PARAM = f"ref={GUR_BRANCH}"
#
GIT_RAW_LINK = Var.slash.join([B_RAW_LINK,
    GIT_USER, GU_REPO, GUR_BRANCH, ])
GIT_API_LINK = Var.slash.join([B_API_LINK,
    GIT_USER, GU_REPO, "contents" ])
BD_RAW_LINK = Var.slash.join([GIT_RAW_LINK,
    str(BASE_DIR), ])
BD_API_LINK = Var.slash.join([
    GIT_API_LINK, str(BASE_DIR), ])
BDF_API_LINK = Var.quest.join([
    BD_API_LINK, LAST_PARAM, ])
#
REDIC_LINK = BASE_DIR if BD_EXISTS else BD_RAW_LINK
# VARS #


# FUNCTINGS - SCAN COMM #
def is_py_script (file_path):
    req_py = ("#!/usr/bin/env python")
    #
    # Auto valid kalau .py
    if not file_path.is_file():
        return False
    if file_path.suffix == ".py":
        return True
    #
    # Cek shebang
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            first_line = f.readline().strip()
        #
        return first_line.startswith(req_py)
    #
    except Exception:
        return False
def normalize_comm (full_path, relative):
    relative_str = str(relative).replace("\\", ":")
    #
    if is_py_script(full_path):
        if relative.suffix == ".py":
            return relative_str[:-3]
        #
        return relative_str
    return None
#
# FUNCTINGS - SCAN COMM #


# FUNCTINGS - GET COMM #
def get_all_commands ():
    comm_files = []
    #
    if BD_EXISTS:
        source = BASE_DIR.rglob("*")
        for item in source:
            if not item.is_file():
                continue
            #
            comm_files.append(str(item))
    else:
        response = requests.get(BDF_API_LINK)
        data = response.json()
        #
        for item in data:
            if item["type"] != "file":
                continue
            #
            comm_files.append(item["name"])
    #
    return comm_files
#
def print_comms (comm_files):
    p_signter = (">+~=-  PY-SYS Commands  -=~+<")
    #
    print(p_signter)
    for cmd in comm_files:
        print(f"  [-] {cmd}")
    print((p_signter) + (Var.enter))
#
# FUNCTINGS - GET COMM #


# FUNCTINGS - EXCING #
def resolve_target (comm_file):
    command_path = comm_file.replace(":", Var.slash)
    target_maps = [
        f"{command_path}.py",
        command_path,
    ]
    for target in target_maps:
        #print ((REDIC_LINK) + "/" + (target))
        #
        if BD_EXISTS:
            target_f = (REDIC_LINK / target)
            if target_f.exists():
                return target_f
        else:
            target_f = Var.slash.join([
                BD_RAW_LINK,
                target
            ])
            response = requests.get(target_f)
            if response.status_code == 200:
                return target_f
    #
    return None
def execute_target(target_f, extra_args):
    # LOCAL #
    if BD_EXISTS:
        subprocess.run(
            [sys.executable, str(target_f), *extra_args],
            check=True
        )
        return
    #
    # REMOTE #
    response = requests.get(target_f)
    if response.status_code != 200:
        print("Failed download target...")
        return
    #
    with tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".py",
        mode="w",
        encoding="utf-8"
    ) as temp_file:
        temp_file.write(response.text)
        temp_path = temp_file.name
    #
    subprocess.run(
        [sys.executable, temp_path, *extra_args],
        check=True
    )
#
# FUNCTINGS - EXCING #


# FUNCTINGS - FINAL #
def sys_work ():
    #
    comm_files = get_all_commands()
    #
    if len(sys.argv) < 2:
        print_comms(comm_files)
        return
    #
    comm_file = sys.argv[1]
    target_f = resolve_target(comm_file)
    if target_f is None:
        msg_404 = f"Command `{comm_file}` is Not-Found..."
        print(msg_404)
        return
    #
    extra_args = sys.argv[2:]
    execute_target(target_f, extra_args)
#
def test ():
    print ((Var.enter) + (f"Local: {BASE_DIR}"))
    print ((f"Remote: {BD_API_LINK}")
        #+ (Var.enter) + (Var.pipe)
    )
    print ((f"Redirect to: {REDIC_LINK}")
        + (Var.enter) + (Var.pipe)
        + (Var.enter) + (Var.pipe))
    #
    #?
    #
#
def main ():
    test()
    #
    #?
    #
    sys_work()
#
# FUNCTINGS - FINAL #


# DISPLAY #
if __name__ == "__main__":
    main()
# DISPLAY #

# ~ ~ ~ ~ ~ #


#
